#!/usr/bin/env sh

make HOST=LINUX TARGET=LINUX MODE=SHARED BITS=32 check-clean clean
make HOST=LINUX TARGET=LINUX MODE=SHARED BITS=64 check-clean clean
make HOST=LINUX TARGET=LINUX MODE=STATIC BITS=32 check-clean clean
make HOST=LINUX TARGET=LINUX MODE=STATIC BITS=64 check-clean clean
make HOST=LINUX TARGET=WINDOWS MODE=SHARED BITS=32 check-clean clean
make HOST=LINUX TARGET=WINDOWS MODE=SHARED BITS=64 check-clean clean
make HOST=LINUX TARGET=WINDOWS MODE=STATIC BITS=32 check-clean clean
make HOST=LINUX TARGET=WINDOWS MODE=STATIC BITS=64 check-clean clean
