#!/usr/bin/env sh

make DEBUG=1 MEMCHECK=1 HOST=LINUX TARGET=LINUX   MODE=SHARED BITS=32 again check-again
make DEBUG=1 MEMCHECK=1 HOST=LINUX TARGET=LINUX   MODE=SHARED BITS=64 again check-again
make DEBUG=1 MEMCHECK=1 HOST=LINUX TARGET=LINUX   MODE=STATIC BITS=32 again check-again
make DEBUG=1 MEMCHECK=1 HOST=LINUX TARGET=LINUX   MODE=STATIC BITS=64 again check-again
make DEBUG=1 MEMCHECK=1 HOST=LINUX TARGET=WINDOWS MODE=SHARED BITS=32 again check-again
make DEBUG=1 MEMCHECK=1 HOST=LINUX TARGET=WINDOWS MODE=SHARED BITS=64 again check-again
make DEBUG=1 MEMCHECK=1 HOST=LINUX TARGET=WINDOWS MODE=STATIC BITS=32 again check-again
make DEBUG=1 MEMCHECK=1 HOST=LINUX TARGET=WINDOWS MODE=STATIC BITS=64 again check-again
